title: Githmi Shanika's Portfolio
description: Slate is a theme for GitHub Pages showcasing Githmi Shanika's projects.
show_downloads: true  # Enable the "Download ZIP" button for visitors
theme: jekyll-theme-slate  # Applying the Slate theme


