title: Githmi Shanika's Portfolio
description: Midnight is a theme for GitHub Pages showcasing Githmi Shanika's projects.
show_downloads: true  # Enable the "Download ZIP" button for visitors
theme: jekyll-theme-midnight  # Applying the Midnight theme
markdown: kramdown  # Specify kramdown as the Markdown processor
