title: Githmi Shanika's Portfolio
description: A brief description of my portfolio showcasing my skills and projects.
title: Midnight theme
description: Midnight is a theme for GitHub Pages.
show_downloads: true
google_analytics:
theme: jekyll-theme-midnight

