title: Githmi Shanika's Portfolio
description: A brief description of my portfolio showcasing my skills and projects.
theme: jekyll-theme-minimal
logo: /assets/img/logo.png
social:
  github: https://github.com/Githmi315
  email: hs24510136@my.sliit.lk

